### ISSUE TITLE
Can not build example with bob.jar for windows and osx

### ISSUE THREAD

**Issue by MaxBrain** [nathan68560/Genetical_Neural_Network#2]
Command:
`java -jar c:/Coding/defold-ci/bob/1.8.1-stable/bob.jar --archive --platform x86_64-win32 resolve distclean build bundle`
Result:
`Error - 2 icon(s) not replaced in c:\Coding\defold-community\Genetical_Neural_Network\build\default\Genetical Neural Network\GeneticalNeuralNetwork.exe using c:\Coding\defold-community\Genetical_Neural_Network\assets\app_icons\appicon.ico`
Expectation:
Normal build

**Comment by nathan68560** [comment]
Thank you for your contribution, I merged the fix (#3) you provided.
